name: Tests Com Docker e Python
on:
  - push

permissions:
  contents: write

jobs:

  test-docker:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.57.0-noble

    steps:
      - uses: actions/checkout@v3
      - name: Run Playwright tests (container)
        run: docker run -it --rm --ipc=host mcr.microsoft.com/playwright/python:v1.57.0-noble /bin/bash -c "pip install -r requirements.txt && pytest tests --tracing=retain-on-failure"
