name: Tests Com Docker e Python
on:
  - push

permissions:
  contents: write

jobs:

  test-docker:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # - name: Ensure browsers are installed
      #   run: python -m playwright install --with-deps

      - name: Run Playwright tests (container)
        run: pytest tests
