name: Tests Com Docker e Python
on:
  - push

permissions:
  contents: write

jobs:

  test-docker:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.55.0-noble
    permissions:
      contents: write # Needed for publishing to GitHub Pages
      pull-requests: write # Needed for posting PR comments (Allure 3 action)
    
    env:
      HOME: /root

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Playwright tests (container)
        continue-on-error: true
        run: xvfb-run --auto-servernum -- pytest tests --alluredir=./allure-results
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }} 
        with:
          name: playwright-traces
          path: test-results/
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history